# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # ACORN-related search parameters
  class AcornSearchParams
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Optional properties
    # If true, then ACORN may be used for the HNSW search based on filters selectivity. Improves search recall for searches with multiple low-selectivity payload filters, at cost of performance.
    @[JSON::Field(key: "enable", emit_null: false)]
    property enable : Bool? = false

    # Maximum selectivity of filters to enable ACORN.  If estimated filters selectivity is higher than this value, ACORN will not be used. Selectivity is estimated as: `estimated number of points satisfying the filters / total number of points`.  0.0 for never, 1.0 for always. Default is 0.4.
    @[JSON::Field(key: "max_selectivity", emit_null: false)]
    property max_selectivity : Float64?

    validates(max_selectivity, Float64, true, maximum: 1, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@enable : Bool? = false, @max_selectivity : Float64? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = max_selectivity_validation_error(@max_selectivity))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(enable, max_selectivity)
  end
end
