# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class AppBuildTelemetry
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    @[JSON::Field(key: "name", emit_null: false)]
    property name : String

    @[JSON::Field(key: "version", emit_null: false)]
    property version : String

    @[JSON::Field(key: "startup", emit_null: false)]
    property startup : Time

    # Optional properties
    @[JSON::Field(key: "features", emit_null: false)]
    property features : AppFeaturesTelemetry?

    @[JSON::Field(key: "runtime_features", emit_null: false)]
    property runtime_features : FeatureFlags?

    @[JSON::Field(key: "low_memory_mode", emit_null: false)]
    property low_memory_mode : LowMemoryMode?

    @[JSON::Field(key: "hnsw_global_config", emit_null: false)]
    property hnsw_global_config : HnswGlobalConfig?

    @[JSON::Field(key: "system", emit_null: false)]
    property system : RunningEnvironmentTelemetry?

    @[JSON::Field(key: "jwt_rbac", emit_null: false)]
    property jwt_rbac : Bool?

    @[JSON::Field(key: "hide_jwt_dashboard", emit_null: false)]
    property hide_jwt_dashboard : Bool?

    @[JSON::Field(key: "audit", emit_null: false)]
    property audit : AuditTelemetry?

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@name : String, @version : String, @startup : Time, @features : AppFeaturesTelemetry? = nil, @runtime_features : FeatureFlags? = nil, @low_memory_mode : LowMemoryMode? = nil, @hnsw_global_config : HnswGlobalConfig? = nil, @system : RunningEnvironmentTelemetry? = nil, @jwt_rbac : Bool? = nil, @hide_jwt_dashboard : Bool? = nil, @audit : AuditTelemetry? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(name, version, features, runtime_features, low_memory_mode, hnsw_global_config, system, jwt_rbac, hide_jwt_dashboard, audit, startup)
  end
end
