# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class AppFeaturesTelemetry
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    @[JSON::Field(key: "debug", emit_null: false)]
    property debug : Bool

    @[JSON::Field(key: "service_debug_feature", emit_null: false)]
    property service_debug_feature : Bool

    @[JSON::Field(key: "recovery_mode", emit_null: false)]
    property recovery_mode : Bool

    @[JSON::Field(key: "gpu", emit_null: false)]
    property gpu : Bool

    @[JSON::Field(key: "rocksdb", emit_null: false)]
    property rocksdb : Bool

    @[JSON::Field(key: "staging", emit_null: false)]
    property staging : Bool

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@debug : Bool, @service_debug_feature : Bool, @recovery_mode : Bool, @gpu : Bool, @rocksdb : Bool, @staging : Bool)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(debug, service_debug_feature, recovery_mode, gpu, rocksdb, staging)
  end
end
