# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class AuditTelemetry
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    @[JSON::Field(key: "dir", emit_null: false)]
    property dir : String

    @[JSON::Field(key: "rotation", emit_null: false)]
    property rotation : String

    @[JSON::Field(key: "max_log_files", emit_null: false)]
    property max_log_files : Int32

    @[JSON::Field(key: "trust_forwarded_headers", emit_null: false)]
    property trust_forwarded_headers : Bool

    @[JSON::Field(key: "log_api", emit_null: false)]
    property log_api : Bool

    # Optional properties
    @[JSON::Field(key: "dir_size_bytes", emit_null: false)]
    property dir_size_bytes : Int32?

    validates(max_log_files, Int32, false, minimum: 0)
    validates(dir_size_bytes, Int32, true, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@dir : String, @rotation : String, @max_log_files : Int32, @trust_forwarded_headers : Bool, @log_api : Bool, @dir_size_bytes : Int32? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = max_log_files_validation_error(@max_log_files))
        invalid_properties.push(msg)
      end
      if (msg = dir_size_bytes_validation_error(@dir_size_bytes))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(dir, rotation, max_log_files, trust_forwarded_headers, log_api, dir_size_bytes)
  end
end
