# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class BinaryQuantizationConfig
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Optional properties
    @[JSON::Field(key: "always_ram", emit_null: false)]
    property always_ram : Bool?

    @[JSON::Field(key: "encoding", emit_null: false)]
    property encoding : BinaryQuantizationEncoding?

    # Asymmetric quantization configuration allows a query to have different quantization than stored vectors. It can increase the accuracy of search at the cost of performance.
    @[JSON::Field(key: "query_encoding", emit_null: false)]
    property query_encoding : BinaryQuantizationQueryEncoding?

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@always_ram : Bool? = nil, @encoding : BinaryQuantizationEncoding? = nil, @query_encoding : BinaryQuantizationQueryEncoding? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(always_ram, encoding, query_encoding)
  end
end
