# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # BinaryQuantizationEncoding (OpenAPI enum). Allowed values: "one_bit", "two_bits", "one_and_half_bits".
  # Represented as `String` so it (de)serialises transparently to/from JSON and YAML,
  # consistent with how inline enums are handled (see the `validates(..., enum: [...])` macro).
  alias BinaryQuantizationEncoding = String
end
