# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # Configuration of the local bm25 models.
  class Bm25Config
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Optional properties
    # Controls term frequency saturation. Higher values mean term frequency has more impact. Default is 1.2
    @[JSON::Field(key: "k", emit_null: false)]
    property k : Float64? = 1.2

    # Controls document length normalization. Ranges from 0 (no normalization) to 1 (full normalization). Higher values mean longer documents have less impact. Default is 0.75.
    @[JSON::Field(key: "b", emit_null: false)]
    property b : Float64? = 0.75

    # Expected average document length in the collection. Default is 256.
    @[JSON::Field(key: "avg_len", emit_null: false)]
    property avg_len : Float64? = 256

    @[JSON::Field(key: "tokenizer", emit_null: false)]
    property tokenizer : TokenizerType?

    # Defines which language to use for text preprocessing. This parameter is used to construct default stopwords filter and stemmer. To disable language-specific processing, set this to `\"language\": \"none\"`. If not specified, English is assumed.
    @[JSON::Field(key: "language", emit_null: false)]
    property language : String?

    # Lowercase the text before tokenization. Default is `true`.
    @[JSON::Field(key: "lowercase", emit_null: false)]
    property lowercase : Bool?

    # If true, normalize tokens by folding accented characters to ASCII (e.g., \"ação\" -> \"acao\"). Default is `false`.
    @[JSON::Field(key: "ascii_folding", emit_null: false)]
    property ascii_folding : Bool?

    # Configuration of the stopwords filter. Supports list of pre-defined languages and custom stopwords. Default: initialized for specified `language` or English if not specified.
    @[JSON::Field(key: "stopwords", emit_null: false)]
    property stopwords : StopwordsInterface?

    # Configuration of the stemmer. Processes tokens to their root form. Default: initialized Snowball stemmer for specified `language` or English if not specified.
    @[JSON::Field(key: "stemmer", emit_null: false)]
    property stemmer : StemmingAlgorithm?

    # Minimum token length to keep. If token is shorter than this, it will be discarded. Default is `None`, which means no minimum length.
    @[JSON::Field(key: "min_token_len", emit_null: false)]
    property min_token_len : Int32?

    # Maximum token length to keep. If token is longer than this, it will be discarded. Default is `None`, which means no maximum length.
    @[JSON::Field(key: "max_token_len", emit_null: false)]
    property max_token_len : Int32?

    validates(min_token_len, Int32, true, minimum: 0)
    validates(max_token_len, Int32, true, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@k : Float64? = 1.2, @b : Float64? = 0.75, @avg_len : Float64? = 256, @tokenizer : TokenizerType? = nil, @language : String? = nil, @lowercase : Bool? = nil, @ascii_folding : Bool? = nil, @stopwords : StopwordsInterface? = nil, @stemmer : StemmingAlgorithm? = nil, @min_token_len : Int32? = nil, @max_token_len : Int32? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = min_token_len_validation_error(@min_token_len))
        invalid_properties.push(msg)
      end
      if (msg = max_token_len_validation_error(@max_token_len))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(k, b, avg_len, tokenizer, language, lowercase, ascii_folding, stopwords, stemmer, min_token_len, max_token_len)
  end
end
