# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class CollectionSnapshotTelemetry
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    @[JSON::Field(key: "id", emit_null: false)]
    property id : String

    # Optional properties
    @[JSON::Field(key: "running_snapshots", emit_null: false)]
    property running_snapshots : Int32?

    @[JSON::Field(key: "running_snapshot_recovery", emit_null: false)]
    property running_snapshot_recovery : Int32?

    @[JSON::Field(key: "total_snapshot_creations", emit_null: false)]
    property total_snapshot_creations : Int32?

    validates(running_snapshots, Int32, true, minimum: 0)
    validates(running_snapshot_recovery, Int32, true, minimum: 0)
    validates(total_snapshot_creations, Int32, true, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@id : String, @running_snapshots : Int32? = nil, @running_snapshot_recovery : Int32? = nil, @total_snapshot_creations : Int32? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = running_snapshots_validation_error(@running_snapshots))
        invalid_properties.push(msg)
      end
      if (msg = running_snapshot_recovery_validation_error(@running_snapshot_recovery))
        invalid_properties.push(msg)
      end
      if (msg = total_snapshot_creations_validation_error(@total_snapshot_creations))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(id, running_snapshots, running_snapshot_recovery, total_snapshot_creations)
  end
end
