# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class DecayParamsExpression
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    @[JSON::Field(key: "x", emit_null: false)]
    property x : Expression

    # Optional properties
    # The target value to start decaying from. Defaults to 0.
    @[JSON::Field(key: "target", emit_null: false)]
    property target : Expression?

    # The scale factor of the decay, in terms of `x`. Defaults to 1.0. Must be a non-zero positive number.
    @[JSON::Field(key: "scale", emit_null: false)]
    property scale : Float32?

    # The midpoint of the decay. Should be between 0 and 1.Defaults to 0.5. Output will be this value when `|x - target| == scale`.
    @[JSON::Field(key: "midpoint", emit_null: false)]
    property midpoint : Float32?

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@x : Expression, @target : Expression? = nil, @scale : Float32? = nil, @midpoint : Float32? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(x, target, scale, midpoint)
  end
end
