# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # Configuration for creating a new dense named vector.  Only includes properties that define the vector space and cannot be changed after creation. Storage type, index type, and quantization are inferred.
  class DenseVectorConfig
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Dimensionality of the vectors
    @[JSON::Field(key: "size", emit_null: false)]
    property size : Int32

    @[JSON::Field(key: "distance", emit_null: false)]
    property distance : Distance

    # Optional properties
    # Configuration for multi-vector points (e.g., ColBERT)
    @[JSON::Field(key: "multivector_config", emit_null: false)]
    property multivector_config : MultiVectorConfig?

    # Element storage type (Float32, Float16, Uint8, Turbo4)
    @[JSON::Field(key: "datatype", emit_null: false)]
    property datatype : VectorStorageDatatype?

    validates(size, Int32, false, maximum: 65536, minimum: 1)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@size : Int32, @distance : Distance, @multivector_config : MultiVectorConfig? = nil, @datatype : VectorStorageDatatype? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = size_validation_error(@size))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(size, distance, multivector_config, datatype)
  end
end
