# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class DistributedCollectionTelemetry
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Collection name
    @[JSON::Field(key: "id", emit_null: false)]
    property id : String

    # Optional properties
    # Shards topology
    @[JSON::Field(key: "shards", emit_null: false)]
    property shards : Array(DistributedShardTelemetry)?

    # Ongoing resharding operations
    @[JSON::Field(key: "reshardings", emit_null: false)]
    property reshardings : Array(ReshardingInfo)?

    # Ongoing shard transfers
    @[JSON::Field(key: "shard_transfers", emit_null: false)]
    property shard_transfers : Array(ShardTransferInfo)?

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@id : String, @shards : Array(DistributedShardTelemetry)? = nil, @reshardings : Array(ReshardingInfo)? = nil, @shard_transfers : Array(ShardTransferInfo)? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(id, shards, reshardings, shard_transfers)
  end
end
