# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class DistributedPeerDetails
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Qdrant version
    @[JSON::Field(key: "version", emit_null: false)]
    property version : String

    # Whether it can participate in leader elections
    @[JSON::Field(key: "is_voter", emit_null: false)]
    property is_voter : Bool

    # Election term
    @[JSON::Field(key: "term", emit_null: false)]
    property term : Int32

    # Latest accepted commit
    @[JSON::Field(key: "commit", emit_null: false)]
    property commit : Int32

    # Number of operations pending for being applied
    @[JSON::Field(key: "num_pending_operations", emit_null: false)]
    property num_pending_operations : Int32

    @[JSON::Field(key: "consensus_thread_status", emit_null: false)]
    property consensus_thread_status : ConsensusThreadStatus

    # Optional properties
    # Consensus role for the peer
    @[JSON::Field(key: "role", emit_null: false)]
    property role : StateRole?

    validates(term, Int32, false, minimum: 0)
    validates(commit, Int32, false, minimum: 0)
    validates(num_pending_operations, Int32, false, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@version : String, @is_voter : Bool, @term : Int32, @commit : Int32, @num_pending_operations : Int32, @consensus_thread_status : ConsensusThreadStatus, @role : StateRole? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = term_validation_error(@term))
        invalid_properties.push(msg)
      end
      if (msg = commit_validation_error(@commit))
        invalid_properties.push(msg)
      end
      if (msg = num_pending_operations_validation_error(@num_pending_operations))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(version, role, is_voter, term, commit, num_pending_operations, consensus_thread_status)
  end
end
