# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class DistributedClusterTelemetry
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    @[JSON::Field(key: "enabled", emit_null: false)]
    property enabled : Bool

    @[JSON::Field(key: "peers", emit_null: false)]
    property peers : Hash(String, DistributedPeerInfo)

    # Optional properties
    @[JSON::Field(key: "number_of_peers", emit_null: false)]
    property number_of_peers : Int32?

    validates(number_of_peers, Int32, true, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@enabled : Bool, @peers : Hash(String, DistributedPeerInfo), @number_of_peers : Int32? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = number_of_peers_validation_error(@number_of_peers))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(enabled, number_of_peers, peers)
  end
end
