# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class DistributedTelemetryData
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    @[JSON::Field(key: "collections", emit_null: false)]
    property collections : Hash(String, DistributedCollectionTelemetry)

    # Optional properties
    @[JSON::Field(key: "cluster", emit_null: false)]
    property cluster : DistributedClusterTelemetry?

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@collections : Hash(String, DistributedCollectionTelemetry), @cluster : DistributedClusterTelemetry? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(collections, cluster)
  end
end
