# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class DistributedReplicaTelemetry
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Peer ID hosting this replica
    @[JSON::Field(key: "peer_id", emit_null: false)]
    property peer_id : Int32

    @[JSON::Field(key: "state", emit_null: false)]
    property state : ReplicaState

    # Optional properties
    # Shard status
    @[JSON::Field(key: "status", emit_null: false)]
    property status : ShardStatus?

    # Total optimized points
    @[JSON::Field(key: "total_optimized_points", emit_null: false)]
    property total_optimized_points : Int32?

    # Estimated vectors size in bytes
    @[JSON::Field(key: "vectors_size_bytes", emit_null: false)]
    property vectors_size_bytes : Int32?

    # Estimated payloads size in bytes
    @[JSON::Field(key: "payloads_size_bytes", emit_null: false)]
    property payloads_size_bytes : Int32?

    # Approximate number of points
    @[JSON::Field(key: "num_points", emit_null: false)]
    property num_points : Int32?

    # Approximate number of vectors
    @[JSON::Field(key: "num_vectors", emit_null: false)]
    property num_vectors : Int32?

    # Approximate number of vectors by name
    @[JSON::Field(key: "num_vectors_by_name", emit_null: false)]
    property num_vectors_by_name : Hash(String, Int32)?

    # Shard cleaning task status. After a resharding, a cleanup task is performed to remove outdated points from this shard.
    @[JSON::Field(key: "shard_cleaning_status", emit_null: false)]
    property shard_cleaning_status : ShardCleanStatusTelemetry?

    # Partial snapshot telemetry
    @[JSON::Field(key: "partial_snapshot", emit_null: false)]
    property partial_snapshot : PartialSnapshotTelemetry?

    validates(peer_id, Int32, false, minimum: 0)
    validates(total_optimized_points, Int32, true, minimum: 0)
    validates(vectors_size_bytes, Int32, true, minimum: 0)
    validates(payloads_size_bytes, Int32, true, minimum: 0)
    validates(num_points, Int32, true, minimum: 0)
    validates(num_vectors, Int32, true, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@peer_id : Int32, @state : ReplicaState, @status : ShardStatus? = nil, @total_optimized_points : Int32? = nil, @vectors_size_bytes : Int32? = nil, @payloads_size_bytes : Int32? = nil, @num_points : Int32? = nil, @num_vectors : Int32? = nil, @num_vectors_by_name : Hash(String, Int32)? = nil, @shard_cleaning_status : ShardCleanStatusTelemetry? = nil, @partial_snapshot : PartialSnapshotTelemetry? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = peer_id_validation_error(@peer_id))
        invalid_properties.push(msg)
      end
      if (msg = total_optimized_points_validation_error(@total_optimized_points))
        invalid_properties.push(msg)
      end
      if (msg = vectors_size_bytes_validation_error(@vectors_size_bytes))
        invalid_properties.push(msg)
      end
      if (msg = payloads_size_bytes_validation_error(@payloads_size_bytes))
        invalid_properties.push(msg)
      end
      if (msg = num_points_validation_error(@num_points))
        invalid_properties.push(msg)
      end
      if (msg = num_vectors_validation_error(@num_vectors))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(peer_id, state, status, total_optimized_points, vectors_size_bytes, payloads_size_bytes, num_points, num_vectors, num_vectors_by_name, shard_cleaning_status, partial_snapshot)
  end
end
