# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class DistributedShardTelemetry
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Shard ID
    @[JSON::Field(key: "id", emit_null: false)]
    property id : Int32

    # Replica information
    @[JSON::Field(key: "replicas", emit_null: false)]
    property replicas : Array(DistributedReplicaTelemetry)

    # Optional properties
    # Optional shard key
    @[JSON::Field(key: "key", emit_null: false)]
    property key : ShardKey?

    validates(id, Int32, false, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@id : Int32, @replicas : Array(DistributedReplicaTelemetry), @key : ShardKey? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = id_validation_error(@id))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(id, key, replicas)
  end
end
