# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # Option variants for text documents. Ether general-purpose options or BM25-specific options. BM25-specific will only take effect if the `qdrant/bm25` is specified as a model.
  # DocumentOptions (OpenAPI anyOf): a value matching at least one of the listed schemas.
  # Implemented as a thin wrapper that (de)serialises by trying each member in order
  # (the first that parses wins), so it transparently handles scalar, array and object members.
  class DocumentOptions
    getter value

    def initialize(@value : Bm25Config)
    end

    def initialize(@value : Hash(String, JSON::Any))
    end

    # List of classes defined in anyOf (OpenAPI v3)
    def self.openapi_any_of
      [
        Bm25Config, Hash(String, JSON::Any),
      ]
    end

    def self.from_json(string_or_io) : self
      from_json_any(JSON.parse(string_or_io))
    end

    def self.new(pull : JSON::PullParser)
      from_json_any(JSON::Any.new(pull))
    end

    def self.from_json_any(data : JSON::Any) : self
      json = data.to_json
      begin
        return new(Bm25Config.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(Hash(String, JSON::Any).from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      raise JSON::ParseException.new("`#{json}` doesn't match any schema listed in DocumentOptions (anyOf)", 0, 0)
    end

    def self.new(ctx : YAML::ParseContext, node : YAML::Nodes::Node)
      begin
        return new(Bm25Config.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(Hash(String, JSON::Any).new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      raise YAML::ParseException.new("doesn't match any schema listed in DocumentOptions (anyOf)", 0, 0)
    end

    def to_json(builder : JSON::Builder)
      @value.to_json(builder)
    end

    def to_yaml(builder : YAML::Nodes::Builder)
      @value.to_yaml(builder)
    end
  end
end
