# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # Expression (OpenAPI anyOf): a value matching at least one of the listed schemas.
  # Implemented as a thin wrapper that (de)serialises by trying each member in order
  # (the first that parses wins), so it transparently handles scalar, array and object members.
  class Expression
    getter value

    def initialize(@value : AbsExpression)
    end

    def initialize(@value : Condition)
    end

    def initialize(@value : DatetimeExpression)
    end

    def initialize(@value : DatetimeKeyExpression)
    end

    def initialize(@value : DivExpression)
    end

    def initialize(@value : ExpDecayExpression)
    end

    def initialize(@value : ExpExpression)
    end

    def initialize(@value : Float32)
    end

    def initialize(@value : GaussDecayExpression)
    end

    def initialize(@value : GeoDistance)
    end

    def initialize(@value : LinDecayExpression)
    end

    def initialize(@value : LnExpression)
    end

    def initialize(@value : Log10Expression)
    end

    def initialize(@value : MultExpression)
    end

    def initialize(@value : NegExpression)
    end

    def initialize(@value : PowExpression)
    end

    def initialize(@value : SqrtExpression)
    end

    def initialize(@value : String)
    end

    def initialize(@value : SumExpression)
    end

    # List of classes defined in anyOf (OpenAPI v3)
    def self.openapi_any_of
      [
        AbsExpression, Condition, DatetimeExpression, DatetimeKeyExpression, DivExpression, ExpDecayExpression, ExpExpression, Float32, GaussDecayExpression, GeoDistance, LinDecayExpression, LnExpression, Log10Expression, MultExpression, NegExpression, PowExpression, SqrtExpression, String, SumExpression,
      ]
    end

    def self.from_json(string_or_io) : self
      from_json_any(JSON.parse(string_or_io))
    end

    def self.new(pull : JSON::PullParser)
      from_json_any(JSON::Any.new(pull))
    end

    def self.from_json_any(data : JSON::Any) : self
      json = data.to_json
      begin
        return new(AbsExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(Condition.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(DatetimeExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(DatetimeKeyExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(DivExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(ExpDecayExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(ExpExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(Float32.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(GaussDecayExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(GeoDistance.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(LinDecayExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(LnExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(Log10Expression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(MultExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(NegExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(PowExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(SqrtExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(String.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(SumExpression.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      raise JSON::ParseException.new("`#{json}` doesn't match any schema listed in Expression (anyOf)", 0, 0)
    end

    def self.new(ctx : YAML::ParseContext, node : YAML::Nodes::Node)
      begin
        return new(AbsExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(Condition.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(DatetimeExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(DatetimeKeyExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(DivExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(ExpDecayExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(ExpExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(Float32.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(GaussDecayExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(GeoDistance.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(LinDecayExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(LnExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(Log10Expression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(MultExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(NegExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(PowExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(SqrtExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(String.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(SumExpression.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      raise YAML::ParseException.new("doesn't match any schema listed in Expression (anyOf)", 0, 0)
    end

    def to_json(builder : JSON::Builder)
      @value.to_json(builder)
    end

    def to_yaml(builder : YAML::Nodes::Builder)
      @value.to_yaml(builder)
    end
  end
end
