# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class FeatureFlags
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Optional properties
    # Magic feature flag that enables all features.  Note that this will only be applied to all flags when passed into [`init_feature_flags`].
    @[JSON::Field(key: "all", emit_null: false)]
    property all : Bool? = false

    # Use incremental HNSW building.  Enabled by default in Qdrant 1.14.1.
    @[JSON::Field(key: "incremental_hnsw_building", emit_null: false)]
    property incremental_hnsw_building : Bool? = true

    # Use appendable quantization in appendable plain segments.  Enabled by default in Qdrant 1.16.0.
    @[JSON::Field(key: "appendable_quantization", emit_null: false)]
    property appendable_quantization : Bool? = true

    # Use single-file mmap in-ram vector storage (InRamMmap)  Enabled by default in Qdrant 1.17.1+
    @[JSON::Field(key: "single_file_mmap_vector_storage", emit_null: false)]
    property single_file_mmap_vector_storage : Bool? = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@all : Bool? = false, @incremental_hnsw_building : Bool? = true, @appendable_quantization : Bool? = true, @single_file_mmap_vector_storage : Bool? = false)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(all, incremental_hnsw_building, appendable_quantization, single_file_mmap_vector_storage)
  end
end
