# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # Usage of the hardware resources, spent to process the request
  class HardwareUsage
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    @[JSON::Field(key: "cpu", emit_null: false)]
    property cpu : Int32

    @[JSON::Field(key: "payload_io_read", emit_null: false)]
    property payload_io_read : Int32

    @[JSON::Field(key: "payload_io_write", emit_null: false)]
    property payload_io_write : Int32

    @[JSON::Field(key: "payload_index_io_read", emit_null: false)]
    property payload_index_io_read : Int32

    @[JSON::Field(key: "payload_index_io_write", emit_null: false)]
    property payload_index_io_write : Int32

    @[JSON::Field(key: "vector_io_read", emit_null: false)]
    property vector_io_read : Int32

    @[JSON::Field(key: "vector_io_write", emit_null: false)]
    property vector_io_write : Int32

    validates(cpu, Int32, false, minimum: 0)
    validates(payload_io_read, Int32, false, minimum: 0)
    validates(payload_io_write, Int32, false, minimum: 0)
    validates(payload_index_io_read, Int32, false, minimum: 0)
    validates(payload_index_io_write, Int32, false, minimum: 0)
    validates(vector_io_read, Int32, false, minimum: 0)
    validates(vector_io_write, Int32, false, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@cpu : Int32, @payload_io_read : Int32, @payload_io_write : Int32, @payload_index_io_read : Int32, @payload_index_io_write : Int32, @vector_io_read : Int32, @vector_io_write : Int32)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = cpu_validation_error(@cpu))
        invalid_properties.push(msg)
      end
      if (msg = payload_io_read_validation_error(@payload_io_read))
        invalid_properties.push(msg)
      end
      if (msg = payload_io_write_validation_error(@payload_io_write))
        invalid_properties.push(msg)
      end
      if (msg = payload_index_io_read_validation_error(@payload_index_io_read))
        invalid_properties.push(msg)
      end
      if (msg = payload_index_io_write_validation_error(@payload_index_io_write))
        invalid_properties.push(msg)
      end
      if (msg = vector_io_read_validation_error(@vector_io_read))
        invalid_properties.push(msg)
      end
      if (msg = vector_io_write_validation_error(@vector_io_write))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(cpu, payload_io_read, payload_io_write, payload_index_io_read, payload_index_io_write, vector_io_read, vector_io_write)
  end
end
