# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class HnswGlobalConfig
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Optional properties
    # Enable HNSW healing if the ratio of missing points is no more than this value. To disable healing completely, set this value to `0.0`.
    @[JSON::Field(key: "healing_threshold", emit_null: false)]
    property healing_threshold : Float64? = 0.3

    validates(healing_threshold, Float64, true, maximum: 1, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@healing_threshold : Float64? = 0.3)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = healing_threshold_validation_error(@healing_threshold))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(healing_threshold)
  end
end
