# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # WARN: Work-in-progress, unimplemented  Image object for embedding. Requires inference infrastructure, unimplemented.
  class Image
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Image data: base64 encoded image or an URL
    @[JSON::Field(key: "image", emit_null: false)]
    property image : JSON::Any

    # Name of the model used to generate the vector. List of available models depends on a provider.
    @[JSON::Field(key: "model", emit_null: false)]
    property model : String

    # Optional properties
    # Parameters for the model Values of the parameters are model-specific
    @[JSON::Field(key: "options", emit_null: false)]
    property options : Hash(String, JSON::Any)?

    validates(model, String, false, min_length: 1)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@image : JSON::Any, @model : String, @options : Hash(String, JSON::Any)? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = model_validation_error(@model))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(image, model, options)
  end
end
