# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class LocalShardTelemetry
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Total number of optimized points since the last start.
    @[JSON::Field(key: "total_optimized_points", emit_null: false)]
    property total_optimized_points : Int32

    # Optional properties
    @[JSON::Field(key: "variant_name", emit_null: false)]
    property variant_name : String?

    @[JSON::Field(key: "status", emit_null: false)]
    property status : ShardStatus?

    # An ESTIMATION of effective amount of bytes used for vectors Do NOT rely on this number unless you know what you are doing
    @[JSON::Field(key: "vectors_size_bytes", emit_null: false)]
    property vectors_size_bytes : Int32?

    # An estimation of the effective amount of bytes used for payloads Do NOT rely on this number unless you know what you are doing
    @[JSON::Field(key: "payloads_size_bytes", emit_null: false)]
    property payloads_size_bytes : Int32?

    # Sum of segment points This is an approximate number Do NOT rely on this number unless you know what you are doing
    @[JSON::Field(key: "num_points", emit_null: false)]
    property num_points : Int32?

    # Sum of number of vectors in all segments This is an approximate number Do NOT rely on this number unless you know what you are doing
    @[JSON::Field(key: "num_vectors", emit_null: false)]
    property num_vectors : Int32?

    # Sum of number of vectors across all segments, grouped by their name. This is an approximate number. Do NOT rely on this number unless you know what you are doing
    @[JSON::Field(key: "num_vectors_by_name", emit_null: false)]
    property num_vectors_by_name : Hash(String, Int32)?

    @[JSON::Field(key: "segments", emit_null: false)]
    property segments : Array(SegmentTelemetry)?

    @[JSON::Field(key: "optimizations", emit_null: false)]
    property optimizations : OptimizerTelemetry?

    @[JSON::Field(key: "async_scorer", emit_null: false)]
    property async_scorer : Bool?

    @[JSON::Field(key: "indexed_only_excluded_vectors", emit_null: false)]
    property indexed_only_excluded_vectors : Hash(String, Int32)?

    # Update queue status
    @[JSON::Field(key: "update_queue", emit_null: false)]
    property update_queue : ShardUpdateQueueInfo?

    validates(total_optimized_points, Int32, false, minimum: 0)
    validates(vectors_size_bytes, Int32, true, minimum: 0)
    validates(payloads_size_bytes, Int32, true, minimum: 0)
    validates(num_points, Int32, true, minimum: 0)
    validates(num_vectors, Int32, true, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@total_optimized_points : Int32, @variant_name : String? = nil, @status : ShardStatus? = nil, @vectors_size_bytes : Int32? = nil, @payloads_size_bytes : Int32? = nil, @num_points : Int32? = nil, @num_vectors : Int32? = nil, @num_vectors_by_name : Hash(String, Int32)? = nil, @segments : Array(SegmentTelemetry)? = nil, @optimizations : OptimizerTelemetry? = nil, @async_scorer : Bool? = nil, @indexed_only_excluded_vectors : Hash(String, Int32)? = nil, @update_queue : ShardUpdateQueueInfo? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = total_optimized_points_validation_error(@total_optimized_points))
        invalid_properties.push(msg)
      end
      if (msg = vectors_size_bytes_validation_error(@vectors_size_bytes))
        invalid_properties.push(msg)
      end
      if (msg = payloads_size_bytes_validation_error(@payloads_size_bytes))
        invalid_properties.push(msg)
      end
      if (msg = num_points_validation_error(@num_points))
        invalid_properties.push(msg)
      end
      if (msg = num_vectors_validation_error(@num_vectors))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(variant_name, status, total_optimized_points, vectors_size_bytes, payloads_size_bytes, num_points, num_vectors, num_vectors_by_name, segments, optimizations, async_scorer, indexed_only_excluded_vectors, update_queue)
  end
end
