# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class MemoryTelemetry
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Total number of bytes in active pages allocated by the application
    @[JSON::Field(key: "active_bytes", emit_null: false)]
    property active_bytes : Int32

    # Total number of bytes allocated by the application
    @[JSON::Field(key: "allocated_bytes", emit_null: false)]
    property allocated_bytes : Int32

    # Total number of bytes dedicated to metadata
    @[JSON::Field(key: "metadata_bytes", emit_null: false)]
    property metadata_bytes : Int32

    # Maximum number of bytes in physically resident data pages mapped
    @[JSON::Field(key: "resident_bytes", emit_null: false)]
    property resident_bytes : Int32

    # Total number of bytes in virtual memory mappings
    @[JSON::Field(key: "retained_bytes", emit_null: false)]
    property retained_bytes : Int32

    validates(active_bytes, Int32, false, minimum: 0)
    validates(allocated_bytes, Int32, false, minimum: 0)
    validates(metadata_bytes, Int32, false, minimum: 0)
    validates(resident_bytes, Int32, false, minimum: 0)
    validates(retained_bytes, Int32, false, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@active_bytes : Int32, @allocated_bytes : Int32, @metadata_bytes : Int32, @resident_bytes : Int32, @retained_bytes : Int32)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = active_bytes_validation_error(@active_bytes))
        invalid_properties.push(msg)
      end
      if (msg = allocated_bytes_validation_error(@allocated_bytes))
        invalid_properties.push(msg)
      end
      if (msg = metadata_bytes_validation_error(@metadata_bytes))
        invalid_properties.push(msg)
      end
      if (msg = resident_bytes_validation_error(@resident_bytes))
        invalid_properties.push(msg)
      end
      if (msg = retained_bytes_validation_error(@retained_bytes))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(active_bytes, allocated_bytes, metadata_bytes, resident_bytes, retained_bytes)
  end
end
