# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # Maximal Marginal Relevance (MMR) algorithm for re-ranking the points.
  class Mmr
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Optional properties
    # Tunable parameter for the MMR algorithm. Determines the balance between diversity and relevance.  A higher value favors diversity (dissimilarity to selected results), while a lower value favors relevance (similarity to the query vector).  Must be in the range [0, 1]. Default value is 0.5.
    @[JSON::Field(key: "diversity", emit_null: false)]
    property diversity : Float32?

    # The maximum number of candidates to consider for re-ranking.  If not specified, the `limit` value is used.
    @[JSON::Field(key: "candidates_limit", emit_null: false)]
    property candidates_limit : Int32?

    validates(diversity, Float32, true, maximum: 1, minimum: 0)
    validates(candidates_limit, Int32, true, maximum: 16384, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@diversity : Float32? = nil, @candidates_limit : Int32? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = diversity_validation_error(@diversity))
        invalid_properties.push(msg)
      end
      if (msg = candidates_limit_validation_error(@candidates_limit))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(diversity, candidates_limit)
  end
end
