# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class OptimizationsSummary
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Number of pending optimizations in the queue. Each optimization will take one or more unoptimized segments and produce one optimized segment.
    @[JSON::Field(key: "queued_optimizations", emit_null: false)]
    property queued_optimizations : Int32

    # Number of unoptimized segments in the queue.
    @[JSON::Field(key: "queued_segments", emit_null: false)]
    property queued_segments : Int32

    # Number of points in unoptimized segments in the queue.
    @[JSON::Field(key: "queued_points", emit_null: false)]
    property queued_points : Int32

    # Number of segments that don't require optimization.
    @[JSON::Field(key: "idle_segments", emit_null: false)]
    property idle_segments : Int32

    validates(queued_optimizations, Int32, false, minimum: 0)
    validates(queued_segments, Int32, false, minimum: 0)
    validates(queued_points, Int32, false, minimum: 0)
    validates(idle_segments, Int32, false, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@queued_optimizations : Int32, @queued_segments : Int32, @queued_points : Int32, @idle_segments : Int32)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = queued_optimizations_validation_error(@queued_optimizations))
        invalid_properties.push(msg)
      end
      if (msg = queued_segments_validation_error(@queued_segments))
        invalid_properties.push(msg)
      end
      if (msg = queued_points_validation_error(@queued_points))
        invalid_properties.push(msg)
      end
      if (msg = idle_segments_validation_error(@idle_segments))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(queued_optimizations, queued_segments, queued_points, idle_segments)
  end
end
