# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class Optimization
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Unique identifier of the optimization process.  After the optimization is complete, a new segment will be created with this UUID.
    @[JSON::Field(key: "uuid", emit_null: false)]
    property uuid : String

    # Name of the optimizer that performed this optimization.
    @[JSON::Field(key: "optimizer", emit_null: false)]
    property optimizer : String

    @[JSON::Field(key: "status", emit_null: false)]
    property status : TrackerStatus

    # Segments being optimized.  After the optimization is complete, these segments will be replaced by the new optimized segment.
    @[JSON::Field(key: "segments", emit_null: false)]
    property segments : Array(OptimizationSegmentInfo)

    @[JSON::Field(key: "progress", emit_null: false)]
    property progress : ProgressTree

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@uuid : String, @optimizer : String, @status : TrackerStatus, @segments : Array(OptimizationSegmentInfo), @progress : ProgressTree)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(uuid, optimizer, status, segments, progress)
  end
end
