# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # Optimizations progress for the collection
  class OptimizationsResponse
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    @[JSON::Field(key: "summary", emit_null: false)]
    property summary : OptimizationsSummary

    # Currently running optimizations.
    @[JSON::Field(key: "running", emit_null: false)]
    property running : Array(Optimization)

    # Optional properties
    # An estimated queue of pending optimizations. Requires `?with=queued`.
    @[JSON::Field(key: "queued", emit_null: false)]
    property queued : Array(PendingOptimization)?

    # Completed optimizations. Requires `?with=completed`. Limited by `?completed_limit=N`.
    @[JSON::Field(key: "completed", emit_null: false)]
    property completed : Array(Optimization)?

    # Segments that don't require optimization. Requires `?with=idle_segments`.
    @[JSON::Field(key: "idle_segments", emit_null: false)]
    property idle_segments : Array(OptimizationSegmentInfo)?

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@summary : OptimizationsSummary, @running : Array(Optimization), @queued : Array(PendingOptimization)? = nil, @completed : Array(Optimization)? = nil, @idle_segments : Array(OptimizationSegmentInfo)? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(summary, running, queued, completed, idle_segments)
  end
end
