# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class OptimizationSegmentInfo
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Unique identifier of the segment.
    @[JSON::Field(key: "uuid", emit_null: false)]
    property uuid : String

    # Number of non-deleted points in the segment.
    @[JSON::Field(key: "points_count", emit_null: false)]
    property points_count : Int32

    validates(points_count, Int32, false, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@uuid : String, @points_count : Int32)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = points_count_validation_error(@points_count))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(uuid, points_count)
  end
end
