# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class PointsList
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    @[JSON::Field(key: "points", emit_null: false)]
    property points : Array(PointStruct)

    # Optional properties
    @[JSON::Field(key: "shard_key", emit_null: false)]
    property shard_key : ShardKeySelector?

    # Filter to apply when updating existing points. Only points matching this filter will be updated. Points that don't match will keep their current state. New points will be inserted regardless of the filter.
    @[JSON::Field(key: "update_filter", emit_null: false)]
    property update_filter : Filter?

    # Mode of the upsert operation: insert_only, upsert (default), update_only
    @[JSON::Field(key: "update_mode", emit_null: false)]
    property update_mode : UpdateMode?

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@points : Array(PointStruct), @shard_key : ShardKeySelector? = nil, @update_filter : Filter? = nil, @update_mode : UpdateMode? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(points, shard_key, update_filter, update_mode)
  end
end
