# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class ProgressTree
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Name of the operation.
    @[JSON::Field(key: "name", emit_null: false)]
    property name : String

    # Optional properties
    # When the operation started.
    @[JSON::Field(key: "started_at", emit_null: false)]
    property started_at : Time?

    # When the operation finished.
    @[JSON::Field(key: "finished_at", emit_null: false)]
    property finished_at : Time?

    # For finished operations, how long they took, in seconds.
    @[JSON::Field(key: "duration_sec", emit_null: false)]
    property duration_sec : Float64?

    # Number of completed units of work, if applicable.
    @[JSON::Field(key: "done", emit_null: false)]
    property done : Int32?

    # Total number of units of work, if applicable and known.
    @[JSON::Field(key: "total", emit_null: false)]
    property total : Int32?

    # Child operations.
    @[JSON::Field(key: "children", emit_null: false)]
    property children : Array(ProgressTree)?

    validates(done, Int32, true, minimum: 0)
    validates(total, Int32, true, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@name : String, @started_at : Time? = nil, @finished_at : Time? = nil, @duration_sec : Float64? = nil, @done : Int32? = nil, @total : Int32? = nil, @children : Array(ProgressTree)? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = done_validation_error(@done))
        invalid_properties.push(msg)
      end
      if (msg = total_validation_error(@total))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(name, started_at, finished_at, duration_sec, done, total, children)
  end
end
