# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # Live snapshot of the adaptive search routing.  `mode` is the runtime currently selected by [`SearchMode`]; `high_cpu_threads` and `high_io_threads` are the blocking-thread budgets of the two underlying runtimes that the adaptive handle routes between.
  class SearchThreadPoolTelemetry
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Currently active mode (`high_cpu` or `high_io`).
    @[JSON::Field(key: "mode", emit_null: false)]
    property mode : String

    # Blocking-thread count of the high-CPU runtime.
    @[JSON::Field(key: "high_cpu_threads", emit_null: false)]
    property high_cpu_threads : Int32

    # Blocking-thread count of the high-IO runtime.
    @[JSON::Field(key: "high_io_threads", emit_null: false)]
    property high_io_threads : Int32

    validates(high_cpu_threads, Int32, false, minimum: 0)
    validates(high_io_threads, Int32, false, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@mode : String, @high_cpu_threads : Int32, @high_io_threads : Int32)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = high_cpu_threads_validation_error(@high_cpu_threads))
        invalid_properties.push(msg)
      end
      if (msg = high_io_threads_validation_error(@high_io_threads))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(mode, high_cpu_threads, high_io_threads)
  end
end
