# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # Aggregated information about segment
  class SegmentInfo
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    @[JSON::Field(key: "uuid", emit_null: false)]
    property uuid : String

    @[JSON::Field(key: "segment_type", emit_null: false)]
    property segment_type : SegmentType

    @[JSON::Field(key: "num_vectors", emit_null: false)]
    property num_vectors : Int32

    @[JSON::Field(key: "num_points", emit_null: false)]
    property num_points : Int32

    @[JSON::Field(key: "num_indexed_vectors", emit_null: false)]
    property num_indexed_vectors : Int32

    @[JSON::Field(key: "num_deleted_vectors", emit_null: false)]
    property num_deleted_vectors : Int32

    # An ESTIMATION of effective amount of bytes used for vectors Do NOT rely on this number unless you know what you are doing
    @[JSON::Field(key: "vectors_size_bytes", emit_null: false)]
    property vectors_size_bytes : Int32

    # An estimation of the effective amount of bytes used for payloads
    @[JSON::Field(key: "payloads_size_bytes", emit_null: false)]
    property payloads_size_bytes : Int32

    @[JSON::Field(key: "ram_usage_bytes", emit_null: false)]
    property ram_usage_bytes : Int32

    @[JSON::Field(key: "disk_usage_bytes", emit_null: false)]
    property disk_usage_bytes : Int32

    @[JSON::Field(key: "is_appendable", emit_null: false)]
    property is_appendable : Bool

    @[JSON::Field(key: "index_schema", emit_null: false)]
    property index_schema : Hash(String, PayloadIndexInfo)

    @[JSON::Field(key: "vector_data", emit_null: false)]
    property vector_data : Hash(String, VectorDataInfo)

    # Optional properties
    @[JSON::Field(key: "num_deferred_points", emit_null: false)]
    property num_deferred_points : Int32?

    @[JSON::Field(key: "num_deleted_deferred_points", emit_null: false)]
    property num_deleted_deferred_points : Int32?

    # Internal ID from which points are deferred (hidden from reads). Only set for appendable segments.
    @[JSON::Field(key: "deferred_internal_id", emit_null: false)]
    property deferred_internal_id : Int32?

    validates(num_vectors, Int32, false, minimum: 0)
    validates(num_points, Int32, false, minimum: 0)
    validates(num_deferred_points, Int32, true, minimum: 0)
    validates(num_deleted_deferred_points, Int32, true, minimum: 0)
    validates(num_indexed_vectors, Int32, false, minimum: 0)
    validates(num_deleted_vectors, Int32, false, minimum: 0)
    validates(vectors_size_bytes, Int32, false, minimum: 0)
    validates(payloads_size_bytes, Int32, false, minimum: 0)
    validates(ram_usage_bytes, Int32, false, minimum: 0)
    validates(disk_usage_bytes, Int32, false, minimum: 0)
    validates(deferred_internal_id, Int32, true, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@uuid : String, @segment_type : SegmentType, @num_vectors : Int32, @num_points : Int32, @num_indexed_vectors : Int32, @num_deleted_vectors : Int32, @vectors_size_bytes : Int32, @payloads_size_bytes : Int32, @ram_usage_bytes : Int32, @disk_usage_bytes : Int32, @is_appendable : Bool, @index_schema : Hash(String, PayloadIndexInfo), @vector_data : Hash(String, VectorDataInfo), @num_deferred_points : Int32? = nil, @num_deleted_deferred_points : Int32? = nil, @deferred_internal_id : Int32? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = num_vectors_validation_error(@num_vectors))
        invalid_properties.push(msg)
      end
      if (msg = num_points_validation_error(@num_points))
        invalid_properties.push(msg)
      end
      if (msg = num_deferred_points_validation_error(@num_deferred_points))
        invalid_properties.push(msg)
      end
      if (msg = num_deleted_deferred_points_validation_error(@num_deleted_deferred_points))
        invalid_properties.push(msg)
      end
      if (msg = num_indexed_vectors_validation_error(@num_indexed_vectors))
        invalid_properties.push(msg)
      end
      if (msg = num_deleted_vectors_validation_error(@num_deleted_vectors))
        invalid_properties.push(msg)
      end
      if (msg = vectors_size_bytes_validation_error(@vectors_size_bytes))
        invalid_properties.push(msg)
      end
      if (msg = payloads_size_bytes_validation_error(@payloads_size_bytes))
        invalid_properties.push(msg)
      end
      if (msg = ram_usage_bytes_validation_error(@ram_usage_bytes))
        invalid_properties.push(msg)
      end
      if (msg = disk_usage_bytes_validation_error(@disk_usage_bytes))
        invalid_properties.push(msg)
      end
      if (msg = deferred_internal_id_validation_error(@deferred_internal_id))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(uuid, segment_type, num_vectors, num_points, num_deferred_points, num_deleted_deferred_points, num_indexed_vectors, num_deleted_vectors, vectors_size_bytes, payloads_size_bytes, ram_usage_bytes, disk_usage_bytes, is_appendable, index_schema, vector_data, deferred_internal_id)
  end
end
