# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class ShardUpdateQueueInfo
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Number of elements in the queue
    @[JSON::Field(key: "length", emit_null: false)]
    property length : Int32

    # Optional properties
    # last operation number processed
    @[JSON::Field(key: "op_num", emit_null: false)]
    property op_num : Int32?

    # Number of points that are deferred (i.e hidden from search as they're not yet optimized).
    @[JSON::Field(key: "deferred_points", emit_null: false)]
    property deferred_points : Int32?

    validates(length, Int32, false, minimum: 0)
    validates(op_num, Int32, true, minimum: 0)
    validates(deferred_points, Int32, true, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@length : Int32, @op_num : Int32? = nil, @deferred_points : Int32? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = length_validation_error(@length))
        invalid_properties.push(msg)
      end
      if (msg = op_num_validation_error(@op_num))
        invalid_properties.push(msg)
      end
      if (msg = deferred_points_validation_error(@deferred_points))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(length, op_num, deferred_points)
  end
end
