# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # SnowballLanguage (OpenAPI enum). Allowed values: "arabic", "armenian", "danish", "dutch", "english", "finnish", "french", "german", "greek", "hungarian", "italian", "norwegian", "portuguese", "romanian", "russian", "spanish", "swedish", "tamil", "turkish".
  # Represented as `String` so it (de)serialises transparently to/from JSON and YAML,
  # consistent with how inline enums are handled (see the `validates(..., enum: [...])` macro).
  alias SnowballLanguage = String
end
