# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class StrictModeConfig
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Optional properties
    # Whether strict mode is enabled for a collection or not.
    @[JSON::Field(key: "enabled", emit_null: false)]
    property enabled : Bool?

    # Max allowed `limit` parameter for all APIs that don't have their own max limit.
    @[JSON::Field(key: "max_query_limit", emit_null: false)]
    property max_query_limit : Int32?

    # Max allowed `timeout` parameter.
    @[JSON::Field(key: "max_timeout", emit_null: false)]
    property max_timeout : Int32?

    # Allow usage of unindexed fields in retrieval based (e.g. search) filters.
    @[JSON::Field(key: "unindexed_filtering_retrieve", emit_null: false)]
    property unindexed_filtering_retrieve : Bool?

    # Allow usage of unindexed fields in filtered updates (e.g. delete by payload).
    @[JSON::Field(key: "unindexed_filtering_update", emit_null: false)]
    property unindexed_filtering_update : Bool?

    # Max HNSW ef value allowed in search parameters.
    @[JSON::Field(key: "search_max_hnsw_ef", emit_null: false)]
    property search_max_hnsw_ef : Int32?

    # Whether exact search is allowed.
    @[JSON::Field(key: "search_allow_exact", emit_null: false)]
    property search_allow_exact : Bool?

    # Max oversampling value allowed in search.
    @[JSON::Field(key: "search_max_oversampling", emit_null: false)]
    property search_max_oversampling : Float64?

    # Max batchsize when upserting
    @[JSON::Field(key: "upsert_max_batchsize", emit_null: false)]
    property upsert_max_batchsize : Int32?

    # Max batchsize when searching
    @[JSON::Field(key: "search_max_batchsize", emit_null: false)]
    property search_max_batchsize : Int32?

    # Max size of a collections vector storage in bytes, ignoring replicas.
    @[JSON::Field(key: "max_collection_vector_size_bytes", emit_null: false)]
    property max_collection_vector_size_bytes : Int32?

    # Max number of read operations per minute per replica
    @[JSON::Field(key: "read_rate_limit", emit_null: false)]
    property read_rate_limit : Int32?

    # Max number of write operations per minute per replica
    @[JSON::Field(key: "write_rate_limit", emit_null: false)]
    property write_rate_limit : Int32?

    # Max size of a collections payload storage in bytes
    @[JSON::Field(key: "max_collection_payload_size_bytes", emit_null: false)]
    property max_collection_payload_size_bytes : Int32?

    # Max number of points estimated in a collection
    @[JSON::Field(key: "max_points_count", emit_null: false)]
    property max_points_count : Int32?

    # Max conditions a filter can have.
    @[JSON::Field(key: "filter_max_conditions", emit_null: false)]
    property filter_max_conditions : Int32?

    # Max size of a condition, eg. items in `MatchAny`.
    @[JSON::Field(key: "condition_max_size", emit_null: false)]
    property condition_max_size : Int32?

    # Multivector strict mode configuration
    @[JSON::Field(key: "multivector_config", emit_null: false)]
    property multivector_config : Hash(String, StrictModeMultivector)?

    # Sparse vector strict mode configuration
    @[JSON::Field(key: "sparse_config", emit_null: false)]
    property sparse_config : Hash(String, StrictModeSparse)?

    # Max number of payload indexes in a collection
    @[JSON::Field(key: "max_payload_index_count", emit_null: false)]
    property max_payload_index_count : Int32?

    # Reject memory-consuming update operations (e.g. upsert, set payload) when the process resident memory exceeds this percentage of total system memory (or cgroup limit). Value in [1, 100]. Applied uniformly to external and internal (replication) traffic — rejection is deterministic so it does not cause replica divergence. Delete operations are not affected, so callers can still free memory.
    @[JSON::Field(key: "max_resident_memory_percent", emit_null: false)]
    property max_resident_memory_percent : Int32?

    # Reject disk-consuming update operations (e.g. upsert, set payload) when the filesystem hosting Qdrant storage is filled above this percentage of its total capacity. Value in [1, 100]. Applied uniformly to external and internal (replication) traffic — rejection is deterministic so it does not cause replica divergence. Delete operations are not affected, so callers can still free disk space. Free space is sampled with a small TTL cache; the gate may take a few seconds to react.
    @[JSON::Field(key: "max_disk_usage_percent", emit_null: false)]
    property max_disk_usage_percent : Int32?

    validates(max_query_limit, Int32, true, minimum: 1)
    validates(max_timeout, Int32, true, minimum: 1)
    validates(search_max_hnsw_ef, Int32, true, minimum: 0)
    validates(upsert_max_batchsize, Int32, true, minimum: 0)
    validates(search_max_batchsize, Int32, true, minimum: 0)
    validates(max_collection_vector_size_bytes, Int32, true, minimum: 0)
    validates(read_rate_limit, Int32, true, minimum: 1)
    validates(write_rate_limit, Int32, true, minimum: 1)
    validates(max_collection_payload_size_bytes, Int32, true, minimum: 0)
    validates(max_points_count, Int32, true, minimum: 1)
    validates(filter_max_conditions, Int32, true, minimum: 0)
    validates(condition_max_size, Int32, true, minimum: 0)
    validates(max_payload_index_count, Int32, true, minimum: 0)
    validates(max_resident_memory_percent, Int32, true, maximum: 100, minimum: 1)
    validates(max_disk_usage_percent, Int32, true, maximum: 100, minimum: 1)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@enabled : Bool? = nil, @max_query_limit : Int32? = nil, @max_timeout : Int32? = nil, @unindexed_filtering_retrieve : Bool? = nil, @unindexed_filtering_update : Bool? = nil, @search_max_hnsw_ef : Int32? = nil, @search_allow_exact : Bool? = nil, @search_max_oversampling : Float64? = nil, @upsert_max_batchsize : Int32? = nil, @search_max_batchsize : Int32? = nil, @max_collection_vector_size_bytes : Int32? = nil, @read_rate_limit : Int32? = nil, @write_rate_limit : Int32? = nil, @max_collection_payload_size_bytes : Int32? = nil, @max_points_count : Int32? = nil, @filter_max_conditions : Int32? = nil, @condition_max_size : Int32? = nil, @multivector_config : Hash(String, StrictModeMultivector)? = nil, @sparse_config : Hash(String, StrictModeSparse)? = nil, @max_payload_index_count : Int32? = nil, @max_resident_memory_percent : Int32? = nil, @max_disk_usage_percent : Int32? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = max_query_limit_validation_error(@max_query_limit))
        invalid_properties.push(msg)
      end
      if (msg = max_timeout_validation_error(@max_timeout))
        invalid_properties.push(msg)
      end
      if (msg = search_max_hnsw_ef_validation_error(@search_max_hnsw_ef))
        invalid_properties.push(msg)
      end
      if (msg = upsert_max_batchsize_validation_error(@upsert_max_batchsize))
        invalid_properties.push(msg)
      end
      if (msg = search_max_batchsize_validation_error(@search_max_batchsize))
        invalid_properties.push(msg)
      end
      if (msg = max_collection_vector_size_bytes_validation_error(@max_collection_vector_size_bytes))
        invalid_properties.push(msg)
      end
      if (msg = read_rate_limit_validation_error(@read_rate_limit))
        invalid_properties.push(msg)
      end
      if (msg = write_rate_limit_validation_error(@write_rate_limit))
        invalid_properties.push(msg)
      end
      if (msg = max_collection_payload_size_bytes_validation_error(@max_collection_payload_size_bytes))
        invalid_properties.push(msg)
      end
      if (msg = max_points_count_validation_error(@max_points_count))
        invalid_properties.push(msg)
      end
      if (msg = filter_max_conditions_validation_error(@filter_max_conditions))
        invalid_properties.push(msg)
      end
      if (msg = condition_max_size_validation_error(@condition_max_size))
        invalid_properties.push(msg)
      end
      if (msg = max_payload_index_count_validation_error(@max_payload_index_count))
        invalid_properties.push(msg)
      end
      if (msg = max_resident_memory_percent_validation_error(@max_resident_memory_percent))
        invalid_properties.push(msg)
      end
      if (msg = max_disk_usage_percent_validation_error(@max_disk_usage_percent))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(enabled, max_query_limit, max_timeout, unindexed_filtering_retrieve, unindexed_filtering_update, search_max_hnsw_ef, search_allow_exact, search_max_oversampling, upsert_max_batchsize, search_max_batchsize, max_collection_vector_size_bytes, read_rate_limit, write_rate_limit, max_collection_payload_size_bytes, max_points_count, filter_max_conditions, condition_max_size, multivector_config, sparse_config, max_payload_index_count, max_resident_memory_percent, max_disk_usage_percent)
  end
end
