# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class StrictModeSparse
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Optional properties
    # Max length of sparse vector
    @[JSON::Field(key: "max_length", emit_null: false)]
    property max_length : Int32?

    validates(max_length, Int32, true, minimum: 1)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@max_length : Int32? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = max_length_validation_error(@max_length))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(max_length)
  end
end
