# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class TelemetryData
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    @[JSON::Field(key: "id", emit_null: false)]
    property id : String

    @[JSON::Field(key: "collections", emit_null: false)]
    property collections : CollectionsTelemetry

    # Optional properties
    @[JSON::Field(key: "app", emit_null: false)]
    property app : AppBuildTelemetry?

    @[JSON::Field(key: "cluster", emit_null: false)]
    property cluster : ClusterTelemetry?

    @[JSON::Field(key: "requests", emit_null: false)]
    property requests : RequestsTelemetry?

    @[JSON::Field(key: "memory", emit_null: false)]
    property memory : MemoryTelemetry?

    @[JSON::Field(key: "hardware", emit_null: false)]
    property hardware : HardwareTelemetry?

    @[JSON::Field(key: "search_pool", emit_null: false)]
    property search_pool : SearchThreadPoolTelemetry?

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@id : String, @collections : CollectionsTelemetry, @app : AppBuildTelemetry? = nil, @cluster : ClusterTelemetry? = nil, @requests : RequestsTelemetry? = nil, @memory : MemoryTelemetry? = nil, @hardware : HardwareTelemetry? = nil, @search_pool : SearchThreadPoolTelemetry? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(id, app, collections, cluster, requests, memory, hardware, search_pool)
  end
end
