# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  class TextIndexParams
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    @[JSON::Field(key: "type", emit_null: false)]
    property _type : TextIndexType

    # Optional properties
    @[JSON::Field(key: "tokenizer", emit_null: false)]
    property tokenizer : TokenizerType?

    # Minimum characters to be tokenized.
    @[JSON::Field(key: "min_token_len", emit_null: false)]
    property min_token_len : Int32?

    # Maximum characters to be tokenized.
    @[JSON::Field(key: "max_token_len", emit_null: false)]
    property max_token_len : Int32?

    # If true, lowercase all tokens. Default: true.
    @[JSON::Field(key: "lowercase", emit_null: false)]
    property lowercase : Bool?

    # If true, normalize tokens by folding accented characters to ASCII (e.g., \"ação\" -> \"acao\"). Default: false.
    @[JSON::Field(key: "ascii_folding", emit_null: false)]
    property ascii_folding : Bool?

    # If true, support phrase matching. Default: false.
    @[JSON::Field(key: "phrase_matching", emit_null: false)]
    property phrase_matching : Bool?

    # Ignore this set of tokens. Can select from predefined languages and/or provide a custom set.
    @[JSON::Field(key: "stopwords", emit_null: false)]
    property stopwords : StopwordsInterface?

    # If true, store the index on disk. Default: false.
    @[JSON::Field(key: "on_disk", emit_null: false)]
    property on_disk : Bool?

    # Algorithm for stemming. Default: disabled.
    @[JSON::Field(key: "stemmer", emit_null: false)]
    property stemmer : StemmingAlgorithm?

    # Enable HNSW graph building for this payload field. If true, builds additional HNSW links (Need payload_m > 0). Default: true.
    @[JSON::Field(key: "enable_hnsw", emit_null: false)]
    property enable_hnsw : Bool?

    validates(min_token_len, Int32, true, minimum: 0)
    validates(max_token_len, Int32, true, minimum: 0)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@_type : TextIndexType, @tokenizer : TokenizerType? = nil, @min_token_len : Int32? = nil, @max_token_len : Int32? = nil, @lowercase : Bool? = nil, @ascii_folding : Bool? = nil, @phrase_matching : Bool? = nil, @stopwords : StopwordsInterface? = nil, @on_disk : Bool? = nil, @stemmer : StemmingAlgorithm? = nil, @enable_hnsw : Bool? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = min_token_len_validation_error(@min_token_len))
        invalid_properties.push(msg)
      end
      if (msg = max_token_len_validation_error(@max_token_len))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(_type, tokenizer, min_token_len, max_token_len, lowercase, ascii_folding, phrase_matching, stopwords, on_disk, stemmer, enable_hnsw)
  end
end
