# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # Tracker object used in telemetry
  class TrackerTelemetry
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Required properties
    # Name of the optimizer
    @[JSON::Field(key: "name", emit_null: false)]
    property name : String

    # UUID of the upcoming segment being created by the optimizer
    @[JSON::Field(key: "uuid", emit_null: false)]
    property uuid : String

    # Internal segment IDs being optimized. These are local and in-memory, meaning that they can refer to different segments after a service restart.
    @[JSON::Field(key: "segment_ids", emit_null: false)]
    property segment_ids : Array(Int32)

    # Segment UUIDs being optimized. Refers to same segments as in `segment_ids`, but trackable across restarts, and reflect their directory name.
    @[JSON::Field(key: "segment_uuids", emit_null: false)]
    property segment_uuids : Array(String)

    @[JSON::Field(key: "status", emit_null: false)]
    property status : TrackerStatus

    # Start time of the optimizer
    @[JSON::Field(key: "start_at", emit_null: false)]
    property start_at : Time

    # Optional properties
    # End time of the optimizer
    @[JSON::Field(key: "end_at", emit_null: false)]
    property end_at : Time?

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@name : String, @uuid : String, @segment_ids : Array(Int32), @segment_uuids : Array(String), @status : TrackerStatus, @start_at : Time, @end_at : Time? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(name, uuid, segment_ids, segment_uuids, status, start_at, end_at)
  end
end
