# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # TurboQuantBitSize (OpenAPI enum). Allowed values: "bits1", "bits1_5", "bits2", "bits4".
  # Represented as `String` so it (de)serialises transparently to/from JSON and YAML,
  # consistent with how inline enums are handled (see the `validates(..., enum: [...])` macro).
  alias TurboQuantBitSize = String
end
