# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # Usage of the hardware resources, spent to process the request
  class Usage
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Optional properties
    @[JSON::Field(key: "hardware", emit_null: false)]
    property hardware : HardwareUsage?

    @[JSON::Field(key: "inference", emit_null: false)]
    property inference : InferenceUsage?

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@hardware : HardwareUsage? = nil, @inference : InferenceUsage? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(hardware, inference)
  end
end
