# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

module Qdrant::Api
  # Configuration for creating a new named vector.  Contains only the immutable properties that define a vector space. Storage type, index, and quantization are determined automatically based on the segment type and can be configured separately later.  Example JSON for a dense vector: ```json { \"dense\": { \"size\": 768, \"distance\": \"Cosine\" } } ```  Example JSON for a sparse vector: ```json { \"sparse\": { \"modifier\": \"Idf\" } } ```
  # VectorNameConfig (OpenAPI anyOf): a value matching at least one of the listed schemas.
  # Implemented as a thin wrapper that (de)serialises by trying each member in order
  # (the first that parses wins), so it transparently handles scalar, array and object members.
  class VectorNameConfig
    getter value

    def initialize(@value : DenseVectorNameConfig)
    end

    def initialize(@value : SparseVectorNameConfig)
    end

    # List of classes defined in anyOf (OpenAPI v3)
    def self.openapi_any_of
      [
        DenseVectorNameConfig, SparseVectorNameConfig,
      ]
    end

    def self.from_json(string_or_io) : self
      from_json_any(JSON.parse(string_or_io))
    end

    def self.new(pull : JSON::PullParser)
      from_json_any(JSON::Any.new(pull))
    end

    def self.from_json_any(data : JSON::Any) : self
      json = data.to_json
      begin
        return new(DenseVectorNameConfig.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(SparseVectorNameConfig.from_json(json))
      rescue JSON::ParseException | ArgumentError | TypeCastError
      end
      raise JSON::ParseException.new("`#{json}` doesn't match any schema listed in VectorNameConfig (anyOf)", 0, 0)
    end

    def self.new(ctx : YAML::ParseContext, node : YAML::Nodes::Node)
      begin
        return new(DenseVectorNameConfig.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      begin
        return new(SparseVectorNameConfig.new(ctx, node))
      rescue YAML::ParseException | ArgumentError | TypeCastError
      end
      raise YAML::ParseException.new("doesn't match any schema listed in VectorNameConfig (anyOf)", 0, 0)
    end

    def to_json(builder : JSON::Builder)
      @value.to_json(builder)
    end

    def to_yaml(builder : YAML::Nodes::Builder)
      @value.to_yaml(builder)
    end
  end
end
