# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

require "../spec_helper"

# Unit tests for Qdrant::Api::CpuEndian
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe Qdrant::Api::CpuEndian do
  describe "JSON round-trip" do
    it "parses an allowed value" do
      value = Qdrant::Api::CpuEndian.from_json(%("little"))
      expect(value).to be_a(Qdrant::Api::CpuEndian)
    end
  end
end
