# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

require "../spec_helper"

# Unit tests for Qdrant::Api::FeatureFlags
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe Qdrant::Api::FeatureFlags do
  describe "JSON round-trip" do
    it "parses an empty JSON object and re-serialises to valid JSON" do
      instance = Qdrant::Api::FeatureFlags.from_json("{}")
      expect(instance).to be_a(Qdrant::Api::FeatureFlags)
      expect(JSON.parse(instance.to_json)).to be_a(JSON::Any)
    end
  end

  describe "#to_h" do
    it "returns a Hash representation" do
      instance = Qdrant::Api::FeatureFlags.from_json("{}")
      expect(instance.to_h).to be_a(Hash(String, JSON::Any))
    end
  end
end
