# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

require "../spec_helper"

# Unit tests for Qdrant::Api::MaxOptimizationThreadsSetting
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe Qdrant::Api::MaxOptimizationThreadsSetting do
  describe "JSON round-trip" do
    it "parses an allowed value" do
      value = Qdrant::Api::MaxOptimizationThreadsSetting.from_json(%("auto"))
      expect(value).to be_a(Qdrant::Api::MaxOptimizationThreadsSetting)
    end
  end
end
