# #Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.24.0
#

require "../spec_helper"

# Unit tests for Qdrant::Api::ShardCleanStatusTelemetry
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe Qdrant::Api::ShardCleanStatusTelemetry do
  describe ".openapi_one_of" do
    it "lists the items referenced in the oneOf array" do
      expect(Qdrant::Api::ShardCleanStatusTelemetry.openapi_one_of).to_not be_empty
    end
  end

  describe ".build" do
    it "is defined on the oneOf union type" do
      expect(Qdrant::Api::ShardCleanStatusTelemetry.responds_to?(:build)).to be_true
    end
  end
end
